### ISSUE TITLE
Video completely covered by black

### ISSUE THREAD

**Issue by Cleverishmoniker** [RobTheFiveNine/nba-league-pass-spoiler-blocker#1]
Just downloaded Chrome so I could use your extension to watch League Pass without the *stupid* spoiler cover (who does that?). It works to set the toggle to on for hide scores, but the entire video is covered with no way to start the video that I can see. Am I missing something? And thanks for addressing the just unbelievable blunder.
Mac with 10.14 Mojave

**Comment by RobTheFiveNine** [comment]
When you go to watch a game, do you see the feed selection modal? (i.e. the thing in the screenshot below asking you to choose a home/away feed)

![Screenshot from 2020-12-20 11-20-03](https://user-images.githubusercontent.com/49003204/102711964-7d156500-42b5-11eb-9355-59e2f7d421f4.png)

Or do you just see this:

![Screenshot from 2020-12-20 11-20-26](https://user-images.githubusercontent.com/49003204/102711973-8d2d4480-42b5-11eb-9005-7fc96634a130.png)

If you're seeing the latter, and never getting the ability to choose a feed - that seems to be a bug in League Pass itself. I've run into it a few times, the only solution I've found is to just refresh the page / try again

**Comment by Cleverishmoniker** [comment]
The second screen with all black is what comes up. I've seen the selection
thing when I've just gone ahead and used Firefox.

-ik
cleverishmoniker@gmail.com

**Comment by RobTheFiveNine** [comment]
The FireFox version of the addon got approved earlier, if you want to try that one, you can find it here: https://addons.mozilla.org/en-GB/firefox/addon/nba-league-pass-spoiler-block/

It's slightly slower in hiding the banner with the spoilers, as FireFox makes it wait a tad longer than Chrome, but it should do the job still 😄

**Comment by Cleverishmoniker** [comment]
Thanks. I didn't even think to check if there was one since it didn't come
up in the Google search like the Chrome one did. Did you write that also?
Do you have a link? NBA chat with CS revealed that it's their glitch and
they're "trying" to solve the problem, though I don't think they really
give much of a damn about their UI, given how kludgey it is.

-ik
cleverishmoniker@gmail.com

**Comment by Cleverishmoniker** [comment]
Christ, I didn't even grok the link in your reply. Thanks.

-ik
cleverishmoniker@gmail.com

**Comment by RobTheFiveNine** [comment]
> Did you write that also?

Yeah, I submitted it to FireFox a bit later than the Chrome version, so it took a bit longer to get approved on there, which is probably why it wasn't in any search results.

> NBA chat with CS revealed that it's their glitch and they're "trying" to solve the problem, though I don't think they really give much of a damn about their UI

There are a lot of bugs in their web app at the moment, it's pretty disappointing. The UI they were using last season wasn't the prettiest of things, but at least it worked! The "keep me signed in" option doesn't even work anymore 😒 Hopefully they will get everything fixed though, something that costs so much to subscribe to shouldn't need people to make browser extensions like this to make them work!
